/* eslint-disable */
// Generated by scripts/generate-elements.mjs — do not edit by hand.
import { NgStrElementEntry } from './elements.model';

export const NGSTR_DOCS_SITE = "https://ngx-stripe.dev";

export const NGSTR_ELEMENTS: NgStrElementEntry[] = [
  {
    "id": "payment",
    "name": "Payment Element",
    "export": "StripePaymentElementComponent",
    "selector": "ngx-stripe-payment",
    "stripeType": "payment",
    "docsPath": "/docs/payment-element",
    "page": "custom",
    "showInNav": true,
    "since": "13.x+",
    "stripeDocs": "https://docs.stripe.com/js/element/payment_element",
    "optionsType": "StripePaymentElementOptions",
    "needsClientSecret": true,
    "summary": "Collect payment details for many methods in one Element. Prefer this over Card Elements for new integrations.",
    "notes": "Wrap in ngx-stripe-elements. Set clientSecret on the parent Elements options before create — nested Elements cannot update clientSecret later. Use @if until the secret exists. doNotCreateUntilClientSecretIsSet defers implicit (non-parent) create.",
    "outputs": [
      "load",
      "blur",
      "change",
      "focus",
      "ready",
      "escape",
      "loaderror"
    ],
    "methods": [
      "fetchUpdates()",
      "update(options)",
      "collapse()"
    ],
    "extraInputs": [
      {
        "name": "doNotCreateUntilClientSecretIsSet",
        "type": "boolean",
        "description": "When true, skip creating the Payment Element until a clientSecret is available (implicit Elements path)."
      }
    ],
    "snippetHtml": "\n@if (elementsOptions.clientSecret) {\n  <ngx-stripe-elements\n    [stripe]=\"stripe\"\n    [elementsOptions]=\"elementsOptions\"\n  >\n    <ngx-stripe-payment />\n  </ngx-stripe-elements>\n}\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripePaymentElementComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripePaymentElementComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n          clientSecret: '{{CLIENT_SECRET}}'\n      };\n    }\n  "
  },
  {
    "id": "express-checkout",
    "name": "Express Checkout Element",
    "export": "StripeExpressCheckoutComponent",
    "selector": "ngx-stripe-express-checkout",
    "stripeType": "expressCheckout",
    "docsPath": "/docs/express-checkout-element",
    "page": "custom",
    "showInNav": true,
    "since": "18.x+",
    "stripeDocs": "https://docs.stripe.com/js/element/express_checkout_element",
    "optionsType": "StripeExpressCheckoutElementOptions",
    "needsClientSecret": true,
    "summary": "Wallet buttons (Apple Pay, Google Pay, Link, PayPal, …) in one Element. Replacement path for Payment Request Button on endive.",
    "notes": "Parent ngx-stripe-elements with a PaymentIntent/SetupIntent clientSecret, or deferred mode + amount (see Express Checkout docs). Bind (clicked) not (click). Confirm via stripe.confirmPayment with the same Elements instance. Checkout Sessions ui_mode=elements use initCheckoutElementsSdk instead.",
    "outputs": [
      "load",
      "blur",
      "focus",
      "ready",
      "escape",
      "loaderror",
      "clicked",
      "confirm",
      "cancel",
      "shippingaddresschange",
      "shippingratechange"
    ],
    "methods": [
      "update(options)"
    ],
    "snippetHtml": "\n@if (elementsOptions.clientSecret) {\n  <ngx-stripe-elements\n    [stripe]=\"stripe\"\n    [elementsOptions]=\"elementsOptions\"\n  >\n    <ngx-stripe-express-checkout />\n  </ngx-stripe-elements>\n}\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeExpressCheckoutComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeExpressCheckoutComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n          clientSecret: '{{CLIENT_SECRET}}'\n      };\n    }\n  "
  },
  {
    "id": "link-authentication",
    "name": "Link Authentication Element",
    "export": "StripeLinkAuthenticationComponent",
    "selector": "ngx-stripe-link-authentication",
    "stripeType": "linkAuthentication",
    "docsPath": "/docs/link-authentication-element",
    "page": "custom",
    "showInNav": true,
    "since": "16.x+",
    "stripeDocs": "https://docs.stripe.com/js/elements_object/create_link_authentication_element",
    "optionsType": "StripeLinkAuthenticationElementOptions",
    "needsClientSecret": true,
    "summary": "Collect email and authenticate returning Link customers on checkout.",
    "notes": "Place inside the same ngx-stripe-elements as Payment Element. Email is collected by the Element — do not also pass it on confirmPayment unless you have a reason to. Stripe now documents this flow as Contact Details (`ngx-stripe-contact-details`); this host remains for the linkAuthentication type.",
    "outputs": [
      "load",
      "blur",
      "change",
      "focus",
      "ready",
      "escape",
      "loaderror"
    ],
    "methods": [],
    "snippetHtml": "\n@if (elementsOptions.clientSecret) {\n  <ngx-stripe-elements\n    [stripe]=\"stripe\"\n    [elementsOptions]=\"elementsOptions\"\n  >\n    <ngx-stripe-link-authentication />\n  </ngx-stripe-elements>\n}\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeLinkAuthenticationComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeLinkAuthenticationComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n          clientSecret: '{{CLIENT_SECRET}}'\n      };\n    }\n  "
  },
  {
    "id": "link-signup",
    "name": "Link Signup Element",
    "export": "StripeLinkSignupComponent",
    "selector": "ngx-stripe-link-signup",
    "stripeType": "linkSignup",
    "docsPath": "/docs/link-signup-element",
    "page": "contract",
    "showInNav": true,
    "since": "22.9.1",
    "stripeDocs": "https://docs.stripe.com/js/elements_object/create_link_signup_element",
    "optionsType": "StripeLinkSignupElementOptions",
    "needsClientSecret": true,
    "optionsInit": "{\n    defaultValues: {\n      email: 'customer@example.com'\n    }\n  }",
    "summary": "Collect Link signup details (email / name / phone defaults) next to Payment Element.",
    "notes": "Requires Link enabled on the Stripe account. Use the same Elements group as Payment Element. Types from @stripe/stripe-js (≥ 9.16).",
    "outputs": [
      "load",
      "blur",
      "focus",
      "ready",
      "escape",
      "loaderror",
      "loaderstart"
    ],
    "methods": [],
    "snippetHtml": "\n@if (elementsOptions.clientSecret) {\n  <ngx-stripe-elements\n    [stripe]=\"stripe\"\n    [elementsOptions]=\"elementsOptions\"\n  >\n    <ngx-stripe-link-signup [options]=\"options\" />\n  </ngx-stripe-elements>\n}\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions, StripeLinkSignupElementOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeLinkSignupComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeLinkSignupComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n          clientSecret: '{{CLIENT_SECRET}}'\n      };\n      options: StripeLinkSignupElementOptions = {\n    defaultValues: {\n      email: 'customer@example.com'\n    }\n  };\n    }\n  "
  },
  {
    "id": "address",
    "name": "Address Element",
    "export": "StripeAddressComponent",
    "selector": "ngx-stripe-address",
    "stripeType": "address",
    "docsPath": "/docs/address-element",
    "page": "custom",
    "showInNav": true,
    "since": "14.x+",
    "stripeDocs": "https://docs.stripe.com/js/elements_object/create_address_element",
    "optionsType": "StripeAddressElementOptions",
    "needsClientSecret": true,
    "summary": "Collect shipping or billing addresses. Autocomplete when used with Payment Element.",
    "notes": "Create with options.mode 'shipping' or 'billing'. Call getValue() to validate and read the address.",
    "outputs": [
      "load",
      "blur",
      "change",
      "focus",
      "ready",
      "escape",
      "loaderror",
      "loaderstart"
    ],
    "methods": [
      "update(options)",
      "getValue()"
    ],
    "snippetHtml": "\n@if (elementsOptions.clientSecret) {\n  <ngx-stripe-elements\n    [stripe]=\"stripe\"\n    [elementsOptions]=\"elementsOptions\"\n  >\n    <ngx-stripe-address />\n  </ngx-stripe-elements>\n}\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeAddressComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeAddressComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n          clientSecret: '{{CLIENT_SECRET}}'\n      };\n    }\n  "
  },
  {
    "id": "contact-details",
    "name": "Contact Details Element",
    "export": "StripeContactDetailsComponent",
    "selector": "ngx-stripe-contact-details",
    "stripeType": "contactDetails",
    "docsPath": "/docs/contact-details-element",
    "page": "contract",
    "showInNav": true,
    "since": "21.9.0",
    "stripeDocs": "https://docs.stripe.com/js/element/contact_details_element",
    "optionsType": "StripeContactDetailsElementOptions",
    "needsClientSecret": true,
    "optionsInit": "{\n    defaultValues: {\n      email: 'customer@example.com'\n    }\n  }",
    "summary": "Collect customer contact details (email) inside Elements.",
    "notes": "Dahlia+ (ngx-stripe 21.9 / 22.9). Stripe’s current name for the Link email Element (was Link Authentication). Listen to (change) for complete / value. Prefer this over ngx-stripe-link-authentication for new work.",
    "outputs": [
      "load",
      "blur",
      "change",
      "focus",
      "ready",
      "escape",
      "loaderror",
      "loaderstart"
    ],
    "methods": [],
    "snippetHtml": "\n@if (elementsOptions.clientSecret) {\n  <ngx-stripe-elements\n    [stripe]=\"stripe\"\n    [elementsOptions]=\"elementsOptions\"\n  >\n    <ngx-stripe-contact-details [options]=\"options\" />\n  </ngx-stripe-elements>\n}\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions, StripeContactDetailsElementOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeContactDetailsComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeContactDetailsComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n          clientSecret: '{{CLIENT_SECRET}}'\n      };\n      options: StripeContactDetailsElementOptions = {\n    defaultValues: {\n      email: 'customer@example.com'\n    }\n  };\n    }\n  "
  },
  {
    "id": "tax-id",
    "name": "Tax Id Element",
    "export": "StripeTaxIdComponent",
    "selector": "ngx-stripe-tax-id",
    "stripeType": "taxId",
    "docsPath": "/docs/tax-id-element",
    "page": "contract",
    "showInNav": true,
    "since": "21.9.0",
    "stripeDocs": "https://docs.stripe.com/js/elements_object/create_tax_id_element",
    "optionsType": "StripeTaxIdElementOptions",
    "needsClientSecret": true,
    "optionsInit": "{\n    visibility: 'always'\n  }",
    "summary": "Collect a customer's tax ID inside Checkout/Elements.",
    "notes": "Dahlia+. Call getValue() after mount. Enable Tax ID collection in Stripe Dashboard / Checkout settings as required by Stripe.",
    "outputs": [
      "load",
      "blur",
      "change",
      "focus",
      "ready",
      "escape",
      "loaderror",
      "loaderstart"
    ],
    "methods": [
      "update(options)",
      "getValue()"
    ],
    "snippetHtml": "\n@if (elementsOptions.clientSecret) {\n  <ngx-stripe-elements\n    [stripe]=\"stripe\"\n    [elementsOptions]=\"elementsOptions\"\n  >\n    <ngx-stripe-tax-id [options]=\"options\" />\n  </ngx-stripe-elements>\n}\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions, StripeTaxIdElementOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeTaxIdComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeTaxIdComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n          clientSecret: '{{CLIENT_SECRET}}'\n      };\n      options: StripeTaxIdElementOptions = {\n    visibility: 'always'\n  };\n    }\n  "
  },
  {
    "id": "terms",
    "name": "Terms Element",
    "export": "StripeTermsComponent",
    "selector": "ngx-stripe-terms",
    "stripeType": "terms",
    "docsPath": "/docs/terms-element",
    "page": "contract",
    "showInNav": true,
    "since": "21.9.0",
    "stripeDocs": "https://docs.stripe.com/js/elements_object/create_terms_element",
    "optionsType": "StripeTermsElementOptions",
    "needsClientSecret": true,
    "summary": "Show Stripe-hosted terms/agreements in the payment form.",
    "notes": "Dahlia+. Options are Stripe-owned (often empty). Pair with Payment Element in the same ngx-stripe-elements.",
    "outputs": [
      "load",
      "blur",
      "focus",
      "ready",
      "escape",
      "loaderror",
      "loaderstart"
    ],
    "methods": [],
    "snippetHtml": "\n@if (elementsOptions.clientSecret) {\n  <ngx-stripe-elements\n    [stripe]=\"stripe\"\n    [elementsOptions]=\"elementsOptions\"\n  >\n    <ngx-stripe-terms />\n  </ngx-stripe-elements>\n}\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeTermsComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeTermsComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n          clientSecret: '{{CLIENT_SECRET}}'\n      };\n    }\n  "
  },
  {
    "id": "currency-selector",
    "name": "Currency Selector Element",
    "export": "StripeCurrencySelectorComponent",
    "selector": "ngx-stripe-currency-selector",
    "stripeType": "currencySelector",
    "docsPath": "/docs/currency-selector-element",
    "page": "contract",
    "showInNav": true,
    "since": "21.9.0",
    "stripeDocs": "https://docs.stripe.com/js/elements_object/create_currency_selector_element",
    "optionsType": "StripeCurrencySelectorElementOptions",
    "needsClientSecret": true,
    "summary": "Let the customer pick a presentment currency when Stripe Adaptive Pricing / currency selection is enabled.",
    "notes": "Dahlia+. Requires a PaymentIntent/SetupIntent whose currency settings allow selection. Stripe owns the option object (currently empty).",
    "outputs": [
      "load",
      "blur",
      "focus",
      "ready",
      "escape",
      "loaderror"
    ],
    "methods": [],
    "snippetHtml": "\n@if (elementsOptions.clientSecret) {\n  <ngx-stripe-elements\n    [stripe]=\"stripe\"\n    [elementsOptions]=\"elementsOptions\"\n  >\n    <ngx-stripe-currency-selector />\n  </ngx-stripe-elements>\n}\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeCurrencySelectorComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeCurrencySelectorComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n          clientSecret: '{{CLIENT_SECRET}}'\n      };\n    }\n  "
  },
  {
    "id": "payment-method-messaging",
    "name": "Payment Method Messaging",
    "export": "StripePaymentMethodMessagingComponent",
    "selector": "ngx-stripe-payment-method-messaging",
    "stripeType": "paymentMethodMessaging",
    "docsPath": "/docs/payment-method-messaging-element",
    "page": "contract",
    "showInNav": true,
    "since": "16.x+",
    "stripeDocs": "https://docs.stripe.com/js/elements_object/create_payment_method_messaging_element",
    "optionsType": "StripePaymentMethodMessagingElementOptions",
    "needsClientSecret": false,
    "optionsInit": "{\n    amount: 9900,\n    currency: 'USD',\n    paymentMethodTypes: ['klarna', 'afterpay_clearpay', 'affirm'],\n    countryCode: 'US'\n  }",
    "summary": "Show buy-now-pay-later / installment messaging (Klarna, Affirm, Afterpay, …) for a given amount.",
    "notes": "Does not collect payment details. amount is in the smallest currency unit. Enable the payment methods on the Stripe account.",
    "examplePath": "/docs/examples/payment-method-messaging",
    "outputs": [
      "load",
      "ready"
    ],
    "methods": [
      "update(options)"
    ],
    "snippetHtml": "\n<ngx-stripe-elements\n  [stripe]=\"stripe\"\n  [elementsOptions]=\"elementsOptions\"\n>\n  <ngx-stripe-payment-method-messaging [options]=\"options\" />\n</ngx-stripe-elements>\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions, StripePaymentMethodMessagingElementOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripePaymentMethodMessagingComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripePaymentMethodMessagingComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n      };\n      options: StripePaymentMethodMessagingElementOptions = {\n    amount: 9900,\n    currency: 'USD',\n    paymentMethodTypes: ['klarna', 'afterpay_clearpay', 'affirm'],\n    countryCode: 'US'\n  };\n    }\n  "
  },
  {
    "id": "card",
    "name": "Card Element",
    "export": "StripeCardComponent",
    "selector": "ngx-stripe-card",
    "stripeType": "card",
    "docsPath": "/docs/card-elements",
    "page": "custom",
    "showInNav": false,
    "since": "1.x+",
    "stripeDocs": "https://docs.stripe.com/js/elements_object/create_card_element",
    "optionsType": "StripeCardElementOptions",
    "needsClientSecret": false,
    "summary": "Single iframe for card number, expiry, and CVC. Prefer Payment Element for new work.",
    "notes": "Split fields use ngx-stripe-card-number, ngx-stripe-card-expiry, ngx-stripe-card-cvc inside ngx-stripe-card-group.",
    "outputs": [
      "load",
      "blur",
      "change",
      "focus",
      "ready",
      "escape"
    ],
    "methods": [
      "update(options)"
    ],
    "snippetHtml": "\n<ngx-stripe-elements\n  [stripe]=\"stripe\"\n  [elementsOptions]=\"elementsOptions\"\n>\n  <ngx-stripe-card />\n</ngx-stripe-elements>\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeCardComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeCardComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n      };\n    }\n  "
  },
  {
    "id": "card-number",
    "name": "Card Number Element",
    "export": "StripeCardNumberComponent",
    "selector": "ngx-stripe-card-number",
    "stripeType": "cardNumber",
    "docsPath": "/docs/card-elements",
    "page": "custom",
    "showInNav": false,
    "since": "1.x+",
    "stripeDocs": "https://docs.stripe.com/js/elements_object/create_card_number_element",
    "optionsType": "StripeCardNumberElementOptions",
    "needsClientSecret": false,
    "summary": "Split Card Element — number field. Use with ngx-stripe-card-group.",
    "notes": "Must sit with expiry and CVC in the same card group.",
    "outputs": [
      "load",
      "blur",
      "change",
      "focus",
      "ready",
      "escape"
    ],
    "methods": [
      "update(options)"
    ],
    "snippetHtml": "\n<ngx-stripe-elements\n  [stripe]=\"stripe\"\n  [elementsOptions]=\"elementsOptions\"\n>\n  <ngx-stripe-card-number />\n</ngx-stripe-elements>\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeCardNumberComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeCardNumberComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n      };\n    }\n  "
  },
  {
    "id": "card-expiry",
    "name": "Card Expiry Element",
    "export": "StripeCardExpiryComponent",
    "selector": "ngx-stripe-card-expiry",
    "stripeType": "cardExpiry",
    "docsPath": "/docs/card-elements",
    "page": "custom",
    "showInNav": false,
    "since": "1.x+",
    "stripeDocs": "https://docs.stripe.com/js/elements_object/create_card_expiry_element",
    "optionsType": "StripeCardExpiryElementOptions",
    "needsClientSecret": false,
    "summary": "Split Card Element — expiry field.",
    "notes": "Use with ngx-stripe-card-group.",
    "outputs": [
      "load",
      "blur",
      "change",
      "focus",
      "ready",
      "escape"
    ],
    "methods": [
      "update(options)"
    ],
    "snippetHtml": "\n<ngx-stripe-elements\n  [stripe]=\"stripe\"\n  [elementsOptions]=\"elementsOptions\"\n>\n  <ngx-stripe-card-expiry />\n</ngx-stripe-elements>\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeCardExpiryComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeCardExpiryComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n      };\n    }\n  "
  },
  {
    "id": "card-cvc",
    "name": "Card CVC Element",
    "export": "StripeCardCvcComponent",
    "selector": "ngx-stripe-card-cvc",
    "stripeType": "cardCvc",
    "docsPath": "/docs/card-elements",
    "page": "custom",
    "showInNav": false,
    "since": "1.x+",
    "stripeDocs": "https://docs.stripe.com/js/elements_object/create_card_cvc_element",
    "optionsType": "StripeCardCvcElementOptions",
    "needsClientSecret": false,
    "summary": "Split Card Element — CVC field.",
    "notes": "Use with ngx-stripe-card-group.",
    "outputs": [
      "load",
      "blur",
      "change",
      "focus",
      "ready",
      "escape"
    ],
    "methods": [
      "update(options)"
    ],
    "snippetHtml": "\n<ngx-stripe-elements\n  [stripe]=\"stripe\"\n  [elementsOptions]=\"elementsOptions\"\n>\n  <ngx-stripe-card-cvc />\n</ngx-stripe-elements>\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeCardCvcComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeCardCvcComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n      };\n    }\n  "
  },
  {
    "id": "iban",
    "name": "IBAN Element",
    "export": "StripeIbanComponent",
    "selector": "ngx-stripe-iban",
    "stripeType": "iban",
    "docsPath": "/docs/iban-element",
    "page": "contract",
    "showInNav": true,
    "since": "6.x+",
    "stripeDocs": "https://docs.stripe.com/js/elements_object/create_iban_element",
    "optionsType": "StripeIbanElementOptions",
    "needsClientSecret": false,
    "optionsInit": "{\n    supportedCountries: ['SEPA']\n  }",
    "summary": "Collect a SEPA IBAN. Often used with createToken / confirmSepaDebitPayment.",
    "notes": "Pass supportedCountries. Confirm with the matching Stripe.js method (e.g. confirmSepaDebitPayment) or createToken for the legacy token flow.",
    "examplePath": "/docs/examples/iban-element",
    "outputs": [
      "load",
      "blur",
      "change",
      "focus",
      "ready",
      "escape"
    ],
    "methods": [
      "update(options)"
    ],
    "snippetHtml": "\n<ngx-stripe-elements\n  [stripe]=\"stripe\"\n  [elementsOptions]=\"elementsOptions\"\n>\n  <ngx-stripe-iban [options]=\"options\" />\n</ngx-stripe-elements>\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions, StripeIbanElementOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeIbanComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeIbanComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n      };\n      options: StripeIbanElementOptions = {\n    supportedCountries: ['SEPA']\n  };\n    }\n  "
  },
  {
    "id": "au-bank-account",
    "name": "AU Bank Account Element",
    "export": "StripeAuBankAccountComponent",
    "selector": "ngx-stripe-au-bank-account",
    "stripeType": "auBankAccount",
    "docsPath": "/docs/au-bank-account-element",
    "page": "contract",
    "showInNav": true,
    "since": "12.x+",
    "stripeDocs": "https://docs.stripe.com/js/elements_object/create_au_bank_account_element",
    "optionsType": "StripeAuBankAccountElementOptions",
    "needsClientSecret": true,
    "summary": "Collect Australian BECS Debit account details.",
    "notes": "Enable au_becs_debit on the Stripe account. Confirm with confirmAuBecsDebitPayment / Setup. BSB + account number are Stripe-hosted.",
    "outputs": [
      "load",
      "blur",
      "change",
      "focus",
      "ready",
      "escape"
    ],
    "methods": [
      "update(options)"
    ],
    "snippetHtml": "\n@if (elementsOptions.clientSecret) {\n  <ngx-stripe-elements\n    [stripe]=\"stripe\"\n    [elementsOptions]=\"elementsOptions\"\n  >\n    <ngx-stripe-au-bank-account />\n  </ngx-stripe-elements>\n}\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeAuBankAccountComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeAuBankAccountComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n          clientSecret: '{{CLIENT_SECRET}}'\n      };\n    }\n  "
  },
  {
    "id": "issuing-card-number",
    "name": "Issuing Card Number",
    "export": "StripeIssuingCardNumberDisplayComponent",
    "selector": "ngx-stripe-issuing-card-number-display",
    "stripeType": "issuingCardNumberDisplay",
    "docsPath": "/docs/issuing-elements",
    "page": "custom",
    "showInNav": false,
    "since": "14.x+",
    "stripeDocs": "https://docs.stripe.com/js/issuing_elements/create_issuing_card_number_display_element",
    "optionsType": "StripeIssuingCardNumberDisplayElementOptions",
    "needsClientSecret": false,
    "summary": "PCI-compliant display of an Issuing card number. Requires an Issuing nonce from your backend.",
    "notes": "Not a checkout Element. Pass issuingCard and nonce in options. See Issuing docs page.",
    "outputs": [
      "load",
      "ready"
    ],
    "methods": [
      "update(options)"
    ],
    "snippetHtml": "\n<ngx-stripe-elements\n  [stripe]=\"stripe\"\n  [elementsOptions]=\"elementsOptions\"\n>\n  <ngx-stripe-issuing-card-number-display />\n</ngx-stripe-elements>\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeIssuingCardNumberDisplayComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeIssuingCardNumberDisplayComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n      };\n    }\n  "
  },
  {
    "id": "issuing-card-cvc",
    "name": "Issuing Card CVC",
    "export": "StripeIssuingCardCvcDisplayComponent",
    "selector": "ngx-stripe-issuing-card-cvc-display",
    "stripeType": "issuingCardCvcDisplay",
    "docsPath": "/docs/issuing-elements",
    "page": "custom",
    "showInNav": false,
    "since": "14.x+",
    "stripeDocs": "https://docs.stripe.com/js/issuing_elements/create_issuing_card_cvc_display_element",
    "optionsType": "StripeIssuingCardCvcDisplayElementOptions",
    "needsClientSecret": false,
    "summary": "PCI-compliant display of an Issuing card CVC.",
    "notes": "Requires Issuing nonce.",
    "outputs": [
      "load",
      "ready"
    ],
    "methods": [
      "update(options)"
    ],
    "snippetHtml": "\n<ngx-stripe-elements\n  [stripe]=\"stripe\"\n  [elementsOptions]=\"elementsOptions\"\n>\n  <ngx-stripe-issuing-card-cvc-display />\n</ngx-stripe-elements>\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeIssuingCardCvcDisplayComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeIssuingCardCvcDisplayComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n      };\n    }\n  "
  },
  {
    "id": "issuing-card-expiry",
    "name": "Issuing Card Expiry",
    "export": "StripeIssuingCardExpiryDisplayComponent",
    "selector": "ngx-stripe-issuing-card-expiry-display",
    "stripeType": "issuingCardExpiryDisplay",
    "docsPath": "/docs/issuing-elements",
    "page": "custom",
    "showInNav": false,
    "since": "14.x+",
    "stripeDocs": "https://docs.stripe.com/js/issuing_elements/create_issuing_card_expiry_display_element",
    "optionsType": "StripeIssuingCardExpiryDisplayElementOptions",
    "needsClientSecret": false,
    "summary": "PCI-compliant display of an Issuing card expiry.",
    "notes": "Requires Issuing nonce.",
    "outputs": [
      "load",
      "ready"
    ],
    "methods": [
      "update(options)"
    ],
    "snippetHtml": "\n<ngx-stripe-elements\n  [stripe]=\"stripe\"\n  [elementsOptions]=\"elementsOptions\"\n>\n  <ngx-stripe-issuing-card-expiry-display />\n</ngx-stripe-elements>\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeIssuingCardExpiryDisplayComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeIssuingCardExpiryDisplayComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n      };\n    }\n  "
  },
  {
    "id": "issuing-card-pin",
    "name": "Issuing Card PIN",
    "export": "StripeIssuingCardPinDisplayComponent",
    "selector": "ngx-stripe-issuing-card-pin-display",
    "stripeType": "issuingCardPinDisplay",
    "docsPath": "/docs/issuing-elements",
    "page": "custom",
    "showInNav": false,
    "since": "14.x+",
    "stripeDocs": "https://docs.stripe.com/js/issuing_elements/create_issuing_card_pin_display_element",
    "optionsType": "StripeIssuingCardPinDisplayElementOptions",
    "needsClientSecret": false,
    "summary": "PCI-compliant display of an Issuing card PIN.",
    "notes": "Requires Issuing nonce.",
    "outputs": [
      "load",
      "ready"
    ],
    "methods": [
      "update(options)"
    ],
    "snippetHtml": "\n<ngx-stripe-elements\n  [stripe]=\"stripe\"\n  [elementsOptions]=\"elementsOptions\"\n>\n  <ngx-stripe-issuing-card-pin-display />\n</ngx-stripe-elements>\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeIssuingCardPinDisplayComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeIssuingCardPinDisplayComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n      };\n    }\n  "
  },
  {
    "id": "issuing-card-copy-button",
    "name": "Issuing Card Copy Button",
    "export": "StripeIssuingCardCopyButtonComponent",
    "selector": "ngx-stripe-issuing-card-copy-button",
    "stripeType": "issuingCardCopyButton",
    "docsPath": "/docs/issuing-elements",
    "page": "custom",
    "showInNav": false,
    "since": "21.9.0",
    "stripeDocs": "https://docs.stripe.com/js/issuing_elements/create_issuing_copy_button_element",
    "optionsType": "StripeIssuingCardCopyButtonElementOptions",
    "needsClientSecret": false,
    "summary": "Copy button paired with Issuing display Elements.",
    "notes": "Dahlia+. to: must reference the Issuing display Element to copy from.",
    "outputs": [
      "load",
      "ready",
      "click"
    ],
    "methods": [
      "update(options)"
    ],
    "snippetHtml": "\n<ngx-stripe-elements\n  [stripe]=\"stripe\"\n  [elementsOptions]=\"elementsOptions\"\n>\n  <ngx-stripe-issuing-card-copy-button />\n</ngx-stripe-elements>\n",
    "snippetTs": "\n    import { Component } from '@angular/core';\n\n    import { StripeElementsOptions } from '@stripe/stripe-js';\n    import {\n      injectStripe,\n      StripeElementsDirective,\n      StripeIssuingCardCopyButtonComponent\n    } from 'ngx-stripe';\n\n    @Component({\n      selector: 'app-checkout',\n      templateUrl: './checkout.component.html',\n      standalone: true,\n      imports: [StripeElementsDirective, StripeIssuingCardCopyButtonComponent]\n    })\n    export class CheckoutComponent {\n      stripe = injectStripe('{{YOUR_PUBLISHABLE_KEY}}');\n      elementsOptions: StripeElementsOptions = {\n        locale: 'en'\n      };\n    }\n  "
  }
];

export function ngStrElementById(id: string): NgStrElementEntry | undefined {
  return NGSTR_ELEMENTS.find((el) => el.id === id);
}

export function ngStrNavElements(): NgStrElementEntry[] {
  return NGSTR_ELEMENTS.filter((el) => el.showInNav);
}

export function ngStrContractElements(): NgStrElementEntry[] {
  return NGSTR_ELEMENTS.filter((el) => el.page === 'contract');
}
